name: Spellcheck

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run spellcheck
        uses: streetsidesoftware/cspell-action@v6
        with:
          config: .cspell.json
          files: |
            **/*.md
            **/*.bash
            **/help.*
